### PR TITLE
cmd: comprehensive, configurable logging

### LINKED ISSUE #107: Provide meaningful information messages
When grafiti is run and encounters an error it does not give meaningful output as to what went wrong:

```
[bharrington@leviathan grafiti]$ AWS_PROFILE=coreosdev ./grafiti --help
Parse resources ID's from CloudTrail events to tag them in AWS, then delete them later.

Usage:
  grafiti [flags]
  grafiti [command]

Available Commands:
  delete      Delete resources in AWS by tag.
  filter      Filter AWS resources by tag.
  help        Help about any command
  parse       Parse resource data from CloudTrail logs.
  tag         Tag resources in AWS.

Flags:
  -c, --config string   Config file (default: $HOME/.grafiti.toml)
      --debug           Enable debug logging.
      --dry-run         Output changes to stdout instead of AWS.
  -h, --help            help for grafiti
  -e, --ignore-errors   Continue processing even when there are API errors.

Use "grafiti [command] --help" for more information about a command.
[bharrington@leviathan grafiti]$ AWS_PROFILE=coreosdev ./grafiti parse 
INFO[0000] Using config file: /home/bharrington/.grafiti.toml 
[bharrington@leviathan grafiti]$ AWS_PROFILE=coreosdev ./grafiti --debug parse 
INFO[0000] Using config file: /home/bharrington/.grafiti.toml 
[bharrington@leviathan grafiti]$ AWS_PROFILE=coreosdev ./grafiti parse  --debug 
INFO[0000] Using config file: /home/bharrington/.grafiti.toml 
```

In this case I have no idea why `--debug` is failing to give any more meaningful output.

### PR DESCRIPTION
**Pull request by estroz**
cmd: comprehensive, configurable logging in package `main`, and pass logger object to `deleter` via `DeleteConfig`

Grafiti error reporting needs to be more verbose and configurable. Errors are now at least logged if not returned and handled by callers.

Fixes #107

### CODE REVIEW

File: arn/arn.go [hunk 1]
```diff
@@ -637,11 +637,7 @@ func MapARNToRTypeAndRName(arnStr ResourceARN) (ResourceType, ResourceName) {
 	var sfx string
 	switch {
 	case strings.HasPrefix(arn, "arn:aws:autoscaling:"):
-		erASG, err := re.Compile("arn:aws:autoscaling:[^:]+:[^:]+:(.+)")
-		if err != nil {
-			fmt.Printf("{\"error\": \"%s\"}\n", err.Error())
-			break
-		}
+		erASG := re.MustCompile("arn:aws:autoscaling:[^:]+:[^:]+:(.+)")
```
Comment (estroz) [inline arn/arn.go]: Switching `Compile` to `MustCompile` because grafiti shouldn't have to handle regex errors arising from compilation of a well-defined pattern (there shouldn't be one).

File: cmd/grafiti/main.go [hunk 2]
```diff
@@ -89,23 +168,26 @@ func initConfig() {
...
+		logger.Errorln("read dummy config file:", err)
+	} else {
+		logger.Info("Using environment variables to configure grafiti.")
 		return
 	}
-
 }
 
 func main() {
 	if err := RootCmd.Execute(); err != nil {
```
Comment (ecordell) [inline cmd/grafiti/main.go]: Instead of `exitWithSuccess` and `exitError`, why don't you use define an Error type for each of the return codes you want, define the command with `RunE`, and then exit with an errorcode defined on the Error type here? Anywhere you want to exitWithSuccess you can return `nil`, everywhere you want to error with a specific code you return that Error type.

Comment (estroz) [inline cmd/grafiti/main.go]: Whenever a command registered as a RunE exits, cobra will print help text. I've found this to be an annoying experience when an error unrelated to help information occurs. With both error functions we can control error text in a relatively simple manner.

Comment (ecordell) [inline cmd/grafiti/main.go]: I think you just need `SilenceUsage` and `SilenceErrors`: https://github.com/spf13/cobra#alternative-error-handling

Comment (estroz) [inline cmd/grafiti/main.go]: @ecordell updated. See #115
